package com.hm.aem.core.listeners;

import org.apache.jackrabbit.api.observation.JackrabbitEvent;
import org.apache.sling.api.resource.ResourceResolver;
import org.apache.sling.api.resource.ResourceResolverFactory;
import org.apache.sling.api.resource.LoginException;
import org.osgi.service.component.annotations.Activate;
import org.osgi.service.component.annotations.Component;
import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

import javax.jcr.*;
import javax.jcr.observation.Event;
import javax.jcr.observation.EventIterator;
import javax.jcr.observation.EventListener;
import javax.jcr.observation.ObservationManager;
import java.util.HashMap;
import java.util.Map;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.apache.sling.jcr.api.SlingRepository;

@Component(service = EventListener.class, immediate = true)
public class JCRNodeEventListener implements EventListener {

    private static final String SERVICE_USER = "event-service-listener";
    private static final Logger logger = LoggerFactory.getLogger(JCRNodeEventListener.class);
    @Reference
    private ResourceResolverFactory resolverFactory;

    @Reference
    private SlingRepository slingRepository;

    private Session session;
    private ObservationManager observationManager;

    @Activate
    protected void activate() throws Exception {
        try {
            
            // Get service user session
            // Map<String, Object> authInfo = new HashMap<>();
            // authInfo.put(ResourceResolverFactory.SUBSERVICE, SERVICE_USER);
            // ResourceResolver resourceResolver = resolverFactory.getServiceResourceResolver(authInfo);
            // session = resourceResolver.adaptTo(Session.class);
            Session session = slingRepository.loginService(SERVICE_USER, null); 


            if (session != null) {
                // Get Observation Manager
                Workspace workspace = session.getWorkspace();
                observationManager = workspace.getObservationManager();

                // Register Event Listener
                observationManager.addEventListener(
                        this,                    // Event Listener Instance
                        Event.NODE_ADDED | Event.NODE_REMOVED | Event.PROPERTY_CHANGED, // Event Types
                        "/content/hm/us/en", // Listening Path
                        true,                     // Deep (include subnodes)
                        null,                     // No specific UUIDs
                        null,                     // No specific node types
                        false                     // Do not listen to events generated by the same session
                );

                System.out.println("JCR Event Listener Registered!");
                logger.info("JCR Event Listener Registered!LOG");
            }

        } catch ( Exception e) {
            e.printStackTrace();
            logger.error("JCR Event Listener Error", e);
        }finally {
            if (session != null) {
                session.logout();
            }
            logger.info("JCR Event Listener finally");
        }
    }

    @Deactivate
    protected void deactivate() {
        try {
            if (observationManager != null) {
                observationManager.removeEventListener(this);
            }
            if (session != null) {
                session.logout();
            }
            System.out.println("JCR Event Listener Unregistered!");
        } catch (RepositoryException e) {
            e.printStackTrace();
        }
    }

    @Override
    public void onEvent(EventIterator eventIterator) {
        try {
            while (eventIterator.hasNext()) {
                Event event = eventIterator.nextEvent();
                String eventPath = event.getPath();

                // Handle different event types
                if (event.getType() == Event.NODE_ADDED) {
                    System.out.println("Node Added: " + eventPath);
                    logger.info("Node Added: " + eventPath);
                } else if (event.getType() == Event.NODE_REMOVED) {
                    System.out.println("Node Removed: " + eventPath);
                    logger.info("Node Removed: " + eventPath);
                } else if (event.getType() == Event.PROPERTY_CHANGED) {
                    System.out.println("Property Changed: " + eventPath);
                    logger.info("Property Changed: " + eventPath);
                }

                // Additional Handling for Jackrabbit Events
                if (event instanceof JackrabbitEvent) {
                    JackrabbitEvent jackrabbitEvent = (JackrabbitEvent) event;
                    if (jackrabbitEvent.isExternal()) {
                        System.out.println("External Event Detected: " + eventPath);
                        logger.info("External Event Detected: " + eventPath);
                    }
                }
            }
        } catch (RepositoryException e) {
            e.printStackTrace();
            logger.error("JCR Event Listener RepositoryException", e);
        }
    }
}
